### PR TITLE
Allow Symfony 6

### PR DESCRIPTION
**Pull request by chalasr**

### CODE REVIEW

**Comment by alexander-schranz** [comment]
Replace of `static::$container` -> `static::getContainer()` should fix the failing tests for Symfony 6 :)

**Comment by alexander-schranz** [comment]
Seems routing file still uses the old `controller:action` instead of `controller::action` format. Not sure if `controller::action` is compatible to symfony 4.4. Else I would discuss with our partners if symfony 4.4 support is still required or if we could drop it 🤔 

https://github.com/sulu/SuluHeadlessBundle/blob/d5eefc8c1ce2567c1deb651304bd6d1aeedad67a/Resources/config/routing_website.yml#L4

**Comment by chalasr** [comment]
The recommended notation should be compatible with 4.4 :) PR updated

**Comment by alexander-schranz** [comment]
Next  one  😄 seems to be https://github.com/sulu/SuluHeadlessBundle/blob/77f100c6516c004358bc963b5d4d76e5db3989af/Controller/HeadlessWebsiteController.php#L60. I think this `$this->get(` need to be now `$this->container->get(` 🤔

**Comment by chalasr** [comment]
Fixed along with a remaining `self::$container` access in tests! 🤞

**Comment by alexander-schranz** [comment]
Nice @chalasr thank you!

**Pull request merged**
