### PR TITLE
Add block settings to BlockResolver

### PR DESCRIPTION
**Pull request by alexandersch**
I have added the block settings logic from https://github.com/sulu/sulu/blob/master/src/Sulu/Component/Content/Types/BlockContentType.php#L375-L404 to the BlockResolver. The code might have to be changed after https://github.com/sulu/sulu/pull/5608 is merged. 

- [ ] write test

### CODE REVIEW

**Comment by nnatter** [comment]
Thanks for working on this! I asked for extracting the relevant functionality of https://github.com/sulu/sulu/pull/5608 into a separate PR: https://github.com/sulu/sulu/pull/5608#discussion_r533301322. Would wait until that discussion is resolved before adding tests here 🙂

**Comment by alexander-schranz** [comment]
@alexandersch sorry for the delay we will discuss this next week to have a fix for this as soon as possible!

**Comment by niklasnatter** [comment]
Hey,
thanks for the PR. I finally found some time to backport the block visitor functionality onto 2.2. This allows us the logic implemented in `sulu/sulu` without the need of adjusting the bundle in the future. The block settings feature should work when these two PRs are merged:
- https://github.com/sulu/sulu/pull/5742
- https://github.com/sulu/SuluHeadlessBundle/pull/69

**Comment by niklasnatter** [comment]
Replaced by #69

**Pull request closed without merging**
